apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.15.1.49   # Replace with the IP address of your NFS server
    path: /jenkins_backup  # Replace with the path to your NFS share
  mountOptions:
    - hard
    - nfsvers=2            # Adjust NFS version if needed

