apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Adjust the requested storage size as needed
  volumeName: nfs-pv  # Specify the name of the PV to use

